### PR TITLE
Add support for SwiftPM resources via Swift 5.3

### LINKED ISSUE #129: I keep getting `JSON file for 'de' locale was not found.` for every locale I enter.
I am working with Server Side Swift and want to use Fakery for testing. But no matter what locale I use, I keep getting a `JSON file for 'de' locale was not found.` error.
I installed Fakery via the Swift Package Manager using the Package.swift file.

### PR DESCRIPTION
**Pull request by Jeehut**
See also this WWDC 2020 session: https://developer.apple.com/videos/play/wwdc2020/10169
Or read the related proposal: https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md

Note that I have only made this compatible when used with SwiftPM. Integration via other dependency managers might be broken.

Fixes #129.

To use this branch before it's merged, use this in your `Package.swift`:
```swift
.package(name: "Fakery", url: "https://github.com/Jeehut/Fakery.git", .branch("master")),
```

### CODE REVIEW

**Comment by zarghol** [comment]
This was 7 days ago. Any plan to merge this ? @vadymmarkov :)

**Comment by vadymmarkov** [comment]
Hi @Jeehut and thanks for your PR! Yes, we definitely want to have proper SPM support, but I think the library should work with other dependency managers because I'm pretty sure it's still being used via CocoaPods or Carthage.

**Comment by LordZardeck** [comment]
@vadymmarkov Any chance on getting this PR adjusted so it can be merged?

**Comment by vadymmarkov** [comment]
@LordZardeck It was already done in https://github.com/vadymmarkov/Fakery/pull/141. I think we can close this one.

**Pull request closed without merging**
