### PR TITLE
Bank

### PR DESCRIPTION
**Pull request by dunyakirkali**
- Generates bank names (only NL)
- Generates Swift codes (only NL)
- Generates IBAN numbers (only NL)

### CODE REVIEW

**Comment by dunyakirkali** [comment]
@vadymmarkov Maybe I should also add some info to the README?

**Comment by vadymmarkov** [comment]
@dunyakirkali yes, would be great!

**Comment by dunyakirkali** [comment]
@vadymmarkov coming up

**Comment by dunyakirkali** [comment]
@vadymmarkov readne is updated

**Comment by dunyakirkali** [comment]
@vadymmarkov İ get the feeling that there is something wrong with travis?

**Comment by vadymmarkov** [comment]
@dunyakirkali I think so too, I've experienced a lot of issues with Travis recently.

**Comment by dunyakirkali** [comment]
Great, thanks!

**Pull request merged**
