### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by diogoguimaraes**
This pull request updates the SwiftyJSON dependency tag.

### CODE REVIEW

**Comment by vadymmarkov** [comment]
@diogoguimaraes :+1:

**Comment by diogoguimaraes** [comment]
@vadymmarkov can you please make a release including this merge? 
Thank you.

**Comment by vadymmarkov** [comment]
@diogoguimaraes Done :wink:

**Comment by diogoguimaraes** [comment]
Thanks! :smile:

**Pull request merged**
