### PR TITLE
Add french country and iso country code

### PR DESCRIPTION
**Pull request by Appsido**

### CODE REVIEW

**Comment by vadymmarkov** [comment]
@Appsido Could you please add new `county()` method in the README?

**Comment by Appsido** [comment]
oops forgot that.

**Comment by Appsido** [comment]
Done ;)

**Comment by vadymmarkov** [comment]
@Appsido Awesome!

**Comment by vadymmarkov** [comment]
🚀

**Comment by Appsido** [comment]
very nice lib BTW

**Pull request merged**
