### PR TITLE
Bank

### PR DESCRIPTION
**Pull request by dunyakirkali**
- Generates BBAN numbers (only NL)

### CODE REVIEW

**Comment by vadymmarkov** [comment]
Hi @dunyakirkali Do you want it to be merged before Swift4 migration?

**Comment by dunyakirkali** [comment]
@vadymmarkov I would actually prefer to wait for the Swift4 branch.

**Comment by vadymmarkov** [comment]
@dunyakirkali Swift 4 branch is merged into master. Would you mind resolving conflicts so we can include it in the next release?

**Comment by dunyakirkali** [comment]
@vadymmarkov I'm on it ;)

**Comment by dunyakirkali** [comment]
@vadymmarkov Ready to merge

**Comment by vadymmarkov** [comment]
Awesome @dunyakirkali, thanks!

**Comment by vadymmarkov** [comment]
@dunyakirkali Version 3.0.0 is out.

**Pull request merged**
