### PR TITLE
Expose Bank class, Add Exposure specs

### PR DESCRIPTION
**Pull request by dunyakirkali**

### CODE REVIEW

**Comment by dunyakirkali** [comment]
@vadymmarkov I had forgotten to expose the bank class so I fixed that. I also added tests for it so that other contributors don't forget to do it. I also made it backwards compatible so that the library can be run on Swift 3 and 4.

**Comment by vadymmarkov** [comment]
@dunyakirkali Great, but I wouldn't add Swift 3 backwards compatibility since we've already released Swift 4 version.

**Comment by dunyakirkali** [comment]
@vadymmarkov Hmm, Could we then have a Swift 3 branch? I'm asking this since I have a project which I haven't updated yet to Swift 4.

**Comment by vadymmarkov** [comment]
Ok, I think it shouldn't be a problem to keep what you've added @dunyakirkali 😉

**Comment by dunyakirkali** [comment]
@vadymmarkov I think it would b better to first extract the swift3 stuff to a branch and merge the rest to master. I'll get back to you in a couple of days.

**Comment by dunyakirkali** [comment]
@vadymmarkov I updated the PR. The backwars compatibility changes are to be found [here](https://github.com/icemobilelab/Fakery/pull/10)

**Comment by vadymmarkov** [comment]
Awesome, thanks!

**Pull request merged**
