### PR TITLE
Feature/vehicle

### PR DESCRIPTION
**Pull request by mderuiter**
Hey @vadymmarkov,

I have added vehicle for Fakery.
I hope you like it.

### CODE REVIEW

**Comment by dunyakirkali** [comment]
@mderuiter Could you also update the README.md with some usage instructions?

**Comment by vadymmarkov** [comment]
Great @mderuiter. Could you also add this generator to https://github.com/vadymmarkov/Fakery/blob/master/Sources/Fakery/Faker.swift to make it accessible.

**Comment by mderuiter** [comment]
@vadymmarkov Thanks for the response. I've added the generator to the faker file.

**Comment by mderuiter** [comment]
@dunyakirkali Thanks for pointing this out. I've updated the README file.

**Comment by vadymmarkov** [comment]
Thanks @mderuiter 👍

**Pull request merged**
